create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  player_name text not null,
  score integer not null,
  created_at timestamp with time zone default now()
);

alter table public.leaderboard enable row level security;

create policy "read leaderboard" on public.leaderboard
  for select using (true);

create policy "insert own score" on public.leaderboard
  for insert with check (auth.uid() = user_id);

create policy "update own score" on public.leaderboard
  for update using (auth.uid() = user_id);

create table if not exists public.leaderboard_weekly (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  player_name text not null,
  score integer not null,
  week_start date not null,
  created_at timestamp with time zone default now()
);

create unique index if not exists leaderboard_weekly_user_week
  on public.leaderboard_weekly(user_id, week_start);

alter table public.leaderboard_weekly enable row level security;

create policy "read weekly leaderboard" on public.leaderboard_weekly
  for select using (true);

create policy "insert own weekly score" on public.leaderboard_weekly
  for insert with check (auth.uid() = user_id);

create policy "update own weekly score" on public.leaderboard_weekly
  for update using (auth.uid() = user_id);

create table if not exists public.ranked_stats (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  player_name text not null,
  rating integer not null default 1000,
  games_played integer not null default 0,
  wins integer not null default 0,
  losses integer not null default 0,
  best_style integer not null default 0,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create unique index if not exists ranked_stats_user_unique
  on public.ranked_stats(user_id);

alter table public.ranked_stats enable row level security;

create policy "read ranked stats" on public.ranked_stats
  for select using (true);

create policy "insert own ranked stats" on public.ranked_stats
  for insert with check (auth.uid() = user_id);

create policy "update own ranked stats" on public.ranked_stats
  for update using (auth.uid() = user_id);

create table if not exists public.match_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mode_id text not null,
  left_points integer not null,
  right_points integer not null,
  style_score integer not null default 0,
  result text not null,
  rating_delta integer not null default 0,
  rating_after integer,
  rally_peak integer not null default 0,
  created_at timestamp with time zone default now()
);

create index if not exists match_history_user_created_idx
  on public.match_history(user_id, created_at desc);

alter table public.match_history enable row level security;

create policy "read own match history" on public.match_history
  for select using (auth.uid() = user_id);

create policy "insert own match history" on public.match_history
  for insert with check (auth.uid() = user_id);

create table if not exists public.player_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  total_wins integer not null default 0,
  total_losses integer not null default 0,
  current_streak integer not null default 0,
  best_streak integer not null default 0,
  max_combo_ever integer not null default 0,
  badges text[] not null default '{}',
  daily_date date not null default current_date,
  daily_matches integer not null default 0,
  daily_wins integer not null default 0,
  daily_best_combo integer not null default 0,
  updated_at timestamp with time zone default now()
);

create unique index if not exists player_progress_user_unique
  on public.player_progress(user_id);

alter table public.player_progress enable row level security;

create policy "read own player progress" on public.player_progress
  for select using (auth.uid() = user_id);

create policy "insert own player progress" on public.player_progress
  for insert with check (auth.uid() = user_id);

create policy "update own player progress" on public.player_progress
  for update using (auth.uid() = user_id);
