create table if not exists public.match_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mode_id text not null,
  left_points integer not null,
  right_points integer not null,
  style_score integer not null default 0,
  result text not null,
  rating_delta integer not null default 0,
  bet_delta integer not null default 0,
  rating_after integer,
  rally_peak integer not null default 0,
  created_at timestamp with time zone default now()
);

alter table public.match_history
  add column if not exists bet_delta integer not null default 0;

create index if not exists match_history_user_created_idx
  on public.match_history(user_id, created_at desc);

alter table public.match_history enable row level security;

drop policy if exists "read own match history" on public.match_history;
drop policy if exists "insert own match history" on public.match_history;

create policy "read own match history" on public.match_history
  for select using (auth.uid() = user_id);

create policy "insert own match history" on public.match_history
  for insert with check (auth.uid() = user_id);


create table if not exists public.player_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  total_wins integer not null default 0,
  total_losses integer not null default 0,
  current_streak integer not null default 0,
  best_streak integer not null default 0,
  max_combo_ever integer not null default 0,
  badges text[] not null default '{}',
  daily_date date not null default current_date,
  daily_matches integer not null default 0,
  daily_wins integer not null default 0,
  daily_best_combo integer not null default 0,
  bet_balance integer not null default 500,
  bet_peak integer not null default 500,
  updated_at timestamp with time zone default now()
);

alter table public.player_progress
  add column if not exists bet_balance integer not null default 500;

alter table public.player_progress
  add column if not exists bet_peak integer not null default 500;

create unique index if not exists player_progress_user_unique
  on public.player_progress(user_id);

alter table public.player_progress enable row level security;

drop policy if exists "read own player progress" on public.player_progress;
drop policy if exists "insert own player progress" on public.player_progress;
drop policy if exists "update own player progress" on public.player_progress;

create policy "read own player progress" on public.player_progress
  for select using (auth.uid() = user_id);

create policy "insert own player progress" on public.player_progress
  for insert with check (auth.uid() = user_id);

create policy "update own player progress" on public.player_progress
  for update using (auth.uid() = user_id);
